import "@/node_modules/react-modal-video/css/modal-video.css"
import "../public/assets/css/bootstrap.css"
import "../public/assets/css/color.css"
import "../public/assets/css/style.css"
import 'swiper/css'
// import "swiper/css/navigation"
import "swiper/css/pagination"
import 'swiper/css/free-mode';
import { poppins } from '@/lib/font'
import Head from "next/head"
import Script from "next/script"
export const metadata = {
    title: 'Medimart Template',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en" className={`${poppins.variable}`}>
            <Script  strategy="lazyOnload" src="https://embed.tawk.to/662e9b46a0c6737bd131eda5/1ht2qoqtk"></Script>
            <body>{children}</body>
        </html>
    )
}
